language: ruby
rvm:
  - 2.3.0
  - 2.4.1
  - 2.5.0
gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  exclude:
    # AR 6.0+ required CRuby 2.4.1+
    - rvm: 2.3.0
    - gemfile: gemfiles/rails_edge.gemfile
before_install: gem install bundler -v 1.11.2
