default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['MYSQL_USER_NAME'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

tako:
  test:
    shard01:
      <<: *default
      database: tako_test_dummy41_shard1
    shard02:
      <<: *default
      database: tako_test_dummy41_shard2
