default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

tako:
  test:
    shard01:
      <<: *default
      database: tako_test_dummy5_shard1
    shard02:
      <<: *default
      database: tako_test_dummy5_shard2
